import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BOARD)

GPIO.setup(35,GPIO.OUT)
GPIO.setup(36,GPIO.OUT)
GPIO.setup(37,GPIO.OUT)
GPIO.setup(38,GPIO.OUT)

#sleep(3)
print("car moving forward")
GPIO.output(35,GPIO.HIGH)
GPIO.output(36,GPIO.LOW)
GPIO.output(37,GPIO.HIGH)
GPIO.output(38,GPIO.LOW)
sleep(2)
print("car moving backward")
GPIO.output(35,GPIO.LOW)
GPIO.output(36,GPIO.HIGH)
GPIO.output(37,GPIO.LOW)
GPIO.output(38,GPIO.HIGH)
sleep(2)
print("car stoped")
GPIO.output(35,GPIO.LOW)
GPIO.output(36,GPIO.LOW)
GPIO.output(37,GPIO.LOW)
GPIO.output(38,GPIO.LOW)
sleep(2)
print("car moving right")
GPIO.output(35,GPIO.HIGH)
GPIO.output(36,GPIO.LOW)
GPIO.output(37,GPIO.LOW)
GPIO.output(38,GPIO.HIGH)
sleep(2)
print("car moving left")
GPIO.output(35,GPIO.LOW)
GPIO.output(36,GPIO.LOW)
GPIO.output(37,GPIO.HIGH)
GPIO.output(38,GPIO.LOW)
sleep(2)
GPIO.cleanup()
